kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-mysql
spec:
  storageClassName: nfs
  capacity:
    storage: 1500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs: 
    path: /data/mysql/data
    server: 192.168.3.100
