kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-www
spec:
  storageClassName: nfs
  capacity:
    storage: 1500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs: 
    path: /data/www
    server: 192.168.3.101
