kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nginx-log
spec:
  storageClassName: nfs
  volumeName: pv-nginx-log
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1500Mi