kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-mysql
spec:
  storageClassName: nfs
  volumeName: pv-mysql
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1500Mi